CREATE VIEW [dbo].[VW_JOBS] AS 
SELECT  J.JOB_ID AS ID_JOB,
		J.NAME   AS NOME,
		CONVERT(VARCHAR(11),CONVERT(DATETIME, CAST(RUN_REQUESTED_DATE AS VARCHAR(11)),103),103) AS DATA_INICIO,
		CONVERT(VARCHAR(11),CONVERT(DATETIME, CAST(STOP_EXECUTION_DATE AS VARCHAR(11)),103),103) AS DATA_FIM,
		CONVERT(VARCHAR(8),RUN_REQUESTED_DATE,108) AS HORA_INICIO,	
		CASE JH.RUN_STATUS WHEN 0 THEN '0'
						   WHEN 1 THEN '2'
						   WHEN 2 THEN '2'
						   WHEN 3 THEN '3'
						   ELSE		   '1'
		END AS STATUS,
		CONVERT(VARCHAR(10),CONVERT(DATETIME,RTRIM(19000101))+(JH.RUN_DURATION * 9 + JH.RUN_DURATION % 10000 * 6 + JH.RUN_DURATION % 100 * 10) / 216E4,108) AS ULTIMA_DURACAO,
		CONVERT(VARCHAR(11),JA.NEXT_SCHEDULED_RUN_DATE,103) AS DATA_PROXIMA_EXEC,
		CONVERT(VARCHAR(8),JA.NEXT_SCHEDULED_RUN_DATE,108)  AS HORA_PROXIMA_EXEC
FROM MSDB.DBO.SYSJOBACTIVITY JA
	 LEFT JOIN MSDB.DBO.SYSJOBHISTORY JH ON JA.JOB_HISTORY_ID = JH.INSTANCE_ID
	 LEFT JOIN MSDB.DBO.SYSJOBS_VIEW J ON JA.JOB_ID = J.JOB_ID
WHERE JA.SESSION_ID = (SELECT MAX(SESSION_ID) FROM MSDB.DBO.SYSJOBACTIVITY)
AND J.NAME LIKE 'BI - %'
AND RUN_REQUESTED_DATE BETWEEN DATEADD(DAY, -5, GETDATE()) AND GETDATE()
